name: Fix PHP Code Style

on:
  workflow_dispatch:
  push:
    paths:
      - '**.php'

jobs:
  fix-php-code-style:
    name: Fix PHP Code Style
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run PHP CS Fixer
        uses: docker://oskarstark/php-cs-fixer-ga:2.18.6

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Fix Backend Code Style
          skip_fetch: true
